/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#faf9f4',
        'surface-dim': '#dbdad5',
        'surface-bright': '#faf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f4ef',
        'surface-container': '#efeee9',
        'surface-container-high': '#e9e8e3',
        'surface-container-highest': '#e3e3de',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#42474d',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        'outline': '#72787e',
        'outline-variant': '#c2c7ce',
        'surface-tint': '#3a627f',
        'primary': '#3a627f',
        'on-primary': '#ffffff',
        'primary-container': '#7da5c4',
        'on-primary-container': '#0a3b55',
        'inverse-primary': '#a3cbec',
        'secondary': '#506351',
        'on-secondary': '#ffffff',
        'secondary-container': '#cde3cc',
        'on-secondary-container': '#526654',
        'tertiary': '#765a05',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#be9c47',
        'on-tertiary-container': '#463400',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#c9e6ff',
        'primary-fixed-dim': '#a3cbec',
        'on-primary-fixed': '#001e2f',
        'on-primary-fixed-variant': '#204b66',
        'secondary-fixed': '#d3e8d2',
        'secondary-fixed-dim': '#b7ccb6',
        'on-secondary-fixed': '#0e1f11',
        'on-secondary-fixed-variant': '#394b3b',
        'tertiary-fixed': '#ffdf96',
        'tertiary-fixed-dim': '#e7c268',
        'on-tertiary-fixed': '#251a00',
        'on-tertiary-fixed-variant': '#5a4400',
        'background': '#faf9f4',
        'on-background': '#1b1c19',
        'surface-variant': '#e3e3de',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '20px',
        margin: '24px',
      },
      fontFamily: {
        h1: ['"Plus Jakarta Sans"', 'sans-serif'],
        h2: ['"Plus Jakarta Sans"', 'sans-serif'],
        h3: ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.04em', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0 12px 40px rgba(58, 98, 127, 0.08)',
        card: '0 4px 18px rgba(58, 98, 127, 0.06)',
      },
    },
  },
  plugins: [],
}
